
let matrix = [
    [1, 2, 3], //FILA 0

    [4, 5, 6], //FILA 1

    ["mango", 8, 9]  //FILA 2
    
];
//console.log("En la matriz hay: ",matrix.length)
//console.log("En la fila 0 hay : ",matrix[0].length)
////console.log(matrix[0][0]);
//console.log(matrix[1][0]);

//matrix[2][0] = 'Mango';
//console.log(matrix[2][0])

//

for (let fila = 0; fila < matrix.length; fila++) {
    for (let columnas = 0; columnas < matrix[fila].length; columnas++) {
    console.log(matrix[fila][columnas])
    }
}


//console.log("hola mundo".length)

